<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Monthly Activity Summary Report - Barangay San Jose</title>
    <style>
        @page {
            margin: 0.5in;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.4;
            margin: 0;
            padding: 0;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #1a365d;
            padding-bottom: 8px;
        }
        .republic {
            font-size: 9px;
            letter-spacing: 2px;
            text-transform: uppercase;
            margin: 0;
        }
        .province {
            font-size: 10px;
            font-weight: bold;
            margin: 2px 0 0 0;
        }
        .barangay {
            font-size: 14px;
            font-weight: bold;
            color: #1a365d;
            margin: 2px 0 0 0;
        }
        .report-title-container {
            text-align: center;
            margin-bottom: 15px;
        }
        .report-title {
            font-size: 16px;
            font-weight: bold;
            color: #1a365d;
            margin: 0;
            text-transform: uppercase;
        }
        .report-subtitle {
            font-size: 10px;
            color: #555;
            margin: 4px 0 0 0;
        }
        
        /* Stats Summary grid */
        .stats-table {
            width: 100%;
            margin-bottom: 15px;
            border-collapse: collapse;
        }
        .stats-card {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            padding: 8px;
            text-align: center;
            width: 25%;
        }
        .stats-val {
            font-size: 16px;
            font-weight: bold;
            color: #1a365d;
        }
        .stats-lbl {
            font-size: 8px;
            color: #4a5568;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-top: 2px;
        }

        /* Standard Data Table */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
            margin-bottom: 15px;
        }
        .data-table th {
            background-color: #1a365d;
            color: #ffffff;
            font-weight: bold;
            text-align: left;
            padding: 5px 6px;
            font-size: 9px;
            text-transform: uppercase;
        }
        .data-table td {
            padding: 5px 6px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 9px;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        
        .section-header {
            font-size: 11px;
            font-weight: bold;
            color: #1a365d;
            margin-top: 15px;
            margin-bottom: 6px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 3px;
            text-transform: uppercase;
        }

        .footer {
            margin-top: 30px;
            font-size: 9px;
            color: #718096;
            width: 100%;
        }
        .sig-table {
            width: 100%;
            margin-top: 20px;
        }
        .sig-block {
            text-align: center;
            width: 50%;
        }
        .sig-line {
            border-bottom: 1px solid #000;
            width: 60%;
            margin: 0 auto 5px auto;
        }
    </style>
</head>
<body>

    <div class="header">
        <p class="republic">Republic of the Philippines</p>
        <p class="province">Province of Metro Manila</p>
        <p class="province">City of Manila</p>
        <p class="barangay">BARANGAY SAN JOSE</p>
    </div>

    <div class="report-title-container">
        <h1 class="report-title">Monthly Activity Summary Report</h1>
        <p class="report-subtitle">
            Reporting Period: {{ \Carbon\Carbon::parse($filters['start_date'] ?? now()->startOfMonth())->format('M d, Y') }} to {{ \Carbon\Carbon::parse($filters['end_date'] ?? now()->endOfMonth())->format('M d, Y') }}<br>
            Generated on: {{ \Carbon\Carbon::parse($generated_at)->format('F d, Y h:i A') }} | Generated By: {{ $generated_by_name }}
        </p>
    </div>

    <!-- Aggregate Stats Cards -->
    <table class="stats-table">
        <tr>
            <td class="stats-card" style="padding-right: 8px;">
                <div class="stats-val">{{ $summary['new_residents'] }}</div>
                <div class="stats-lbl">New Residents Enrolled</div>
            </td>
            <td class="stats-card" style="padding-right: 8px; padding-left: 8px;">
                <div class="stats-val">{{ $summary['documents_processed'] }}</div>
                <div class="stats-lbl">Certificates Issued</div>
            </td>
            <td class="stats-card" style="padding-right: 8px; padding-left: 8px;">
                <div class="stats-val">Php {{ number_format($summary['revenue_generated'], 2) }}</div>
                <div class="stats-lbl">Revenue Collected</div>
            </td>
            <td class="stats-card" style="padding-left: 8px;">
                <div class="stats-val">{{ $summary['blotters_filed'] }} / {{ $summary['blotters_settled'] }}</div>
                <div class="stats-lbl">Blotters Filed / Settled</div>
            </td>
        </tr>
    </table>

    <!-- Barangay Registry Operations Breakdowns -->
    <div class="section-header">1. Resident Enrolments By Purok</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Purok / Zone</th>
                <th>New Registrants Enrolled</th>
                <th>Cumulative Registry Size</th>
            </tr>
        </thead>
        <tbody>
            @foreach($purok_stats as $purok)
                <tr>
                    <td style="font-weight: bold;">{{ $purok['name'] }}</td>
                    <td>{{ $purok['new_count'] }}</td>
                    <td style="font-weight: bold;">{{ $purok['total_count'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-header">2. Certificate Issuances & Clearance Revenue</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Certificate Type</th>
                <th>Requests Filed</th>
                <th>Approved Requests</th>
                <th>Released Requests</th>
                <th style="text-align: right;">Total Fee Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($document_stats as $doc)
                <tr>
                    <td style="font-weight: bold; text-transform: capitalize;">{{ $doc['type'] }}</td>
                    <td>{{ $doc['filed'] }}</td>
                    <td>{{ $doc['approved'] }}</td>
                    <td>{{ $doc['released'] }}</td>
                    <td style="text-align: right; font-weight: bold; color: #1a365d;">Php {{ number_format($doc['revenue'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-header">3. Incident Blotter & Resolutions</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Case Status</th>
                <th>Cases Transited / Recorded</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="font-weight: bold;">Filed / New</td>
                <td style="font-weight: bold;">{{ $summary['blotters_filed'] }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Settled Cases</td>
                <td style="font-weight: bold; color: #166534;">{{ $summary['blotters_settled'] }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Escalated / Unresolved Cases</td>
                <td style="font-weight: bold; color: #991b1b;">{{ $summary['blotters_escalated'] }}</td>
            </tr>
        </tbody>
    </table>

    <table class="sig-table">
        <tr>
            <td class="sig-block">
                <div style="font-size: 9px; margin-bottom: 25px;">Prepared by:</div>
                <div style="font-weight: bold;">{{ strtoupper($generated_by_name) }}</div>
                <div style="font-size: 8px; color: #555;">Barangay Personnel / Staff</div>
            </td>
            <td class="sig-block">
                <div style="font-size: 9px; margin-bottom: 25px;">Attested by:</div>
                <div class="sig-line"></div>
                <div style="font-weight: bold;">HON. JUAN DELA CRUZ</div>
                <div style="font-size: 8px; color: #555;">Barangay Chairman</div>
            </td>
        </tr>
    </table>

    <div class="footer" style="text-align: center; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 8px;">
        <p style="margin: 0;">Barangay San Jose Information System — Confidential Monthly Report Summary</p>
    </div>

</body>
</html>
