<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Residents Registry Report - Barangay San Jose</title>
    <style>
        @page {
            margin: 0.5in;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.4;
            margin: 0;
            padding: 0;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1a365d;
            padding-bottom: 10px;
        }
        .republic {
            font-size: 10px;
            letter-spacing: 2px;
            text-transform: uppercase;
            margin: 0;
        }
        .province {
            font-size: 11px;
            font-weight: bold;
            margin: 2px 0 0 0;
        }
        .barangay {
            font-size: 15px;
            font-weight: bold;
            color: #1a365d;
            margin: 2px 0 0 0;
        }
        .report-title-container {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-title {
            font-size: 18px;
            font-weight: bold;
            color: #1a365d;
            margin: 0;
            text-transform: uppercase;
        }
        .report-subtitle {
            font-size: 11px;
            color: #555;
            margin: 5px 0 0 0;
        }
        
        /* Stats Summary grid */
        .stats-table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }
        .stats-card {
            background-color: #f7fafc;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            padding: 10px;
            text-align: center;
            width: 25%;
        }
        .stats-val {
            font-size: 18px;
            font-weight: bold;
            color: #1a365d;
        }
        .stats-lbl {
            font-size: 9px;
            color: #4a5568;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-top: 2px;
        }

        /* Standard Data Table */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .data-table th {
            background-color: #1a365d;
            color: #ffffff;
            font-weight: bold;
            text-align: left;
            padding: 6px 8px;
            font-size: 10px;
            text-transform: uppercase;
        }
        .data-table td {
            padding: 6px 8px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 10px;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        
        .section-header {
            font-size: 12px;
            font-weight: bold;
            color: #1a365d;
            margin-top: 20px;
            margin-bottom: 8px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 4px;
        }

        .footer {
            margin-top: 40px;
            font-size: 10px;
            color: #718096;
            width: 100%;
        }
        .sig-table {
            width: 100%;
            margin-top: 30px;
        }
        .sig-block {
            text-align: center;
            width: 50%;
        }
        .sig-line {
            border-bottom: 1px solid #000;
            width: 70%;
            margin: 0 auto 5px auto;
        }
    </style>
</head>
<body>

    <div class="header">
        <p class="republic">Republic of the Philippines</p>
        <p class="province">Province of Metro Manila</p>
        <p class="province">City of Manila</p>
        <p class="barangay">BARANGAY SAN JOSE</p>
    </div>

    <div class="report-title-container">
        <h1 class="report-title">Residents Registry Report</h1>
        <p class="report-subtitle">Generated on: {{ \Carbon\Carbon::parse($generated_at)->format('F d, Y h:i A') }} | Generated By: {{ $generated_by_name }}</p>
    </div>

    <!-- Aggregate Stats Cards -->
    <table class="stats-table">
        <tr>
            <td class="stats-card" style="padding-right: 10px;">
                <div class="stats-val">{{ $summary['total_residents'] }}</div>
                <div class="stats-lbl">Total Residents</div>
            </td>
            <td class="stats-card" style="padding-right: 10px; padding-left: 10px;">
                <div class="stats-val">{{ $summary['male_count'] }}</div>
                <div class="stats-lbl">Male Residents</div>
            </td>
            <td class="stats-card" style="padding-right: 10px; padding-left: 10px;">
                <div class="stats-val">{{ $summary['female_count'] }}</div>
                <div class="stats-lbl">Female Residents</div>
            </td>
            <td class="stats-card" style="padding-left: 10px;">
                <div class="stats-val">{{ $summary['senior_count'] }}</div>
                <div class="stats-lbl">Seniors (60+)</div>
            </td>
        </tr>
    </table>

    <div class="section-header">Demographic Breakdowns</div>
    <table style="width: 100%; margin-bottom: 20px;">
        <tr>
            <!-- Purok Breakdown -->
            <td style="width: 48%; vertical-align: top; padding-right: 4%;">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>Purok / Zone</th>
                            <th style="text-align: right;">Resident Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($purok_breakdown as $purok)
                            <tr>
                                <td>{{ $purok->purok_name }}</td>
                                <td style="text-align: right; font-weight: bold;">{{ $purok->residents_count }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </td>
            
            <!-- Age Group Breakdown -->
            <td style="width: 48%; vertical-align: top;">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>Age Bracket</th>
                            <th style="text-align: right;">Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Seniors (60+)</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['senior_count'] }}</td>
                        </tr>
                        <tr>
                            <td>Adults (18-59)</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['adult_count'] }}</td>
                        </tr>
                        <tr>
                            <td>Youth (12-17)</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['youth_count'] }}</td>
                        </tr>
                        <tr>
                            <td>Children (<12)</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['child_count'] }}</td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </table>

    <div class="section-header">Residents Listing</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>No.</th>
                <th>Full Name</th>
                <th>Purok</th>
                <th>Gender</th>
                <th>Civil Status</th>
                <th>Age</th>
                <th>Occupation</th>
                <th>Status Flags</th>
            </tr>
        </thead>
        <tbody>
            @forelse($residents as $index => $resident)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td style="font-weight: bold;">{{ $resident->last_name }}, {{ $resident->first_name }}</td>
                    <td>{{ $resident->purok->purok_name }}</td>
                    <td style="text-transform: capitalize;">{{ $resident->gender }}</td>
                    <td style="text-transform: capitalize;">{{ $resident->civil_status }}</td>
                    <td>{{ \Carbon\Carbon::parse($resident->date_of_birth)->age }}</td>
                    <td>{{ $resident->occupation ?? 'N/A' }}</td>
                    <td>
                        @if($resident->is_voter) <span style="background-color:#dbeafe; color:#1e40af; padding: 1px 3px; border-radius: 2px; font-size: 8px;">Voter</span> @endif
                        @if($resident->is_indigent) <span style="background-color:#dcfce7; color:#166534; padding: 1px 3px; border-radius: 2px; font-size: 8px;">Indigent</span> @endif
                        @if($resident->is_pwd) <span style="background-color:#fef9c3; color:#854d0e; padding: 1px 3px; border-radius: 2px; font-size: 8px;">PWD</span> @endif
                        @if($resident->is_senior_citizen) <span style="background-color:#f3e8ff; color:#6b21a8; padding: 1px 3px; border-radius: 2px; font-size: 8px;">Senior</span> @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center; color: #718096; padding: 20px;">No resident records found matching filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <table class="sig-table">
        <tr>
            <td class="sig-block">
                <div style="font-size: 10px; margin-bottom: 25px;">Prepared by:</div>
                <div style="font-weight: bold;">{{ strtoupper($generated_by_name) }}</div>
                <div style="font-size: 9px; color: #555;">Barangay Personnel / Staff</div>
            </td>
            <td class="sig-block">
                <div style="font-size: 10px; margin-bottom: 25px;">Attested by:</div>
                <div class="sig-line"></div>
                <div style="font-weight: bold;">HON. JUAN DELA CRUZ</div>
                <div style="font-size: 9px; color: #555;">Barangay Chairman</div>
            </td>
        </tr>
    </table>

    <div class="footer" style="text-align: center; margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 10px;">
        <p style="margin: 0;">Barangay San Jose Information System — Confidential Administrative Document</p>
    </div>

</body>
</html>
