<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blotter & Incident Records Report - Barangay San Jose</title>
    <style>
        @page {
            margin: 0.5in;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.4;
            margin: 0;
            padding: 0;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1a365d;
            padding-bottom: 10px;
        }
        .republic {
            font-size: 10px;
            letter-spacing: 2px;
            text-transform: uppercase;
            margin: 0;
        }
        .province {
            font-size: 11px;
            font-weight: bold;
            margin: 2px 0 0 0;
        }
        .barangay {
            font-size: 15px;
            font-weight: bold;
            color: #1a365d;
            margin: 2px 0 0 0;
        }
        .report-title-container {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-title {
            font-size: 18px;
            font-weight: bold;
            color: #1a365d;
            margin: 0;
            text-transform: uppercase;
        }
        .report-subtitle {
            font-size: 11px;
            color: #555;
            margin: 5px 0 0 0;
        }
        
        /* Stats Summary grid */
        .stats-table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }
        .stats-card {
            background-color: #f7fafc;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            padding: 10px;
            text-align: center;
            width: 25%;
        }
        .stats-val {
            font-size: 18px;
            font-weight: bold;
            color: #1a365d;
        }
        .stats-lbl {
            font-size: 9px;
            color: #4a5568;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-top: 2px;
        }

        /* Standard Data Table */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .data-table th {
            background-color: #1a365d;
            color: #ffffff;
            font-weight: bold;
            text-align: left;
            padding: 6px 8px;
            font-size: 10px;
            text-transform: uppercase;
        }
        .data-table td {
            padding: 6px 8px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 10px;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        
        .section-header {
            font-size: 12px;
            font-weight: bold;
            color: #1a365d;
            margin-top: 20px;
            margin-bottom: 8px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 4px;
        }

        .footer {
            margin-top: 40px;
            font-size: 10px;
            color: #718096;
            width: 100%;
        }
        .sig-table {
            width: 100%;
            margin-top: 30px;
        }
        .sig-block {
            text-align: center;
            width: 50%;
        }
        .sig-line {
            border-bottom: 1px solid #000;
            width: 70%;
            margin: 0 auto 5px auto;
        }
        
        .status-badge {
            padding: 2px 5px;
            border-radius: 2px;
            font-size: 9px;
            font-weight: bold;
            text-transform: capitalize;
        }
    </style>
</head>
<body>

    <div class="header">
        <p class="republic">Republic of the Philippines</p>
        <p class="province">Province of Metro Manila</p>
        <p class="province">City of Manila</p>
        <p class="barangay">BARANGAY SAN JOSE</p>
    </div>

    <div class="report-title-container">
        <h1 class="report-title">Blotter & Incident Records Report</h1>
        <p class="report-subtitle">Generated on: {{ \Carbon\Carbon::parse($generated_at)->format('F d, Y h:i A') }} | Generated By: {{ $generated_by_name }}</p>
    </div>

    <!-- Aggregate Stats Cards -->
    <table class="stats-table">
        <tr>
            <td class="stats-card" style="padding-right: 10px;">
                <div class="stats-val">{{ $summary['total_blotters'] }}</div>
                <div class="stats-lbl">Total Blotters</div>
            </td>
            <td class="stats-card" style="padding-right: 10px; padding-left: 10px;">
                <div class="stats-val">{{ $summary['filed_count'] }}</div>
                <div class="stats-lbl">Filed / New</div>
            </td>
            <td class="stats-card" style="padding-right: 10px; padding-left: 10px;">
                <div class="stats-val">{{ $summary['investigation_count'] }}</div>
                <div class="stats-lbl">Under Investigation</div>
            </td>
            <td class="stats-card" style="padding-left: 10px;">
                <div class="stats-val">{{ $summary['settled_count'] }}</div>
                <div class="stats-lbl">Settled Cases</div>
            </td>
        </tr>
    </table>

    <div class="section-header">Incident Summaries</div>
    <table style="width: 100%; margin-bottom: 20px;">
        <tr>
            <!-- Status Breakdown -->
            <td style="width: 48%; vertical-align: top; padding-right: 4%;">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>Case Status</th>
                            <th style="text-align: right;">Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Filed</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['filed_count'] }}</td>
                        </tr>
                        <tr>
                            <td>Under Investigation</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['investigation_count'] }}</td>
                        </tr>
                        <tr>
                            <td>Settled</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['settled_count'] }}</td>
                        </tr>
                        <tr>
                            <td>Escalated</td>
                            <td style="text-align: right; font-weight: bold;">{{ $summary['escalated_count'] }}</td>
                        </tr>
                    </tbody>
                </table>
            </td>
            
            <!-- Type Breakdown -->
            <td style="width: 48%; vertical-align: top;">
                <table class="data-table">
                    <thead>
                        <tr>
                            <th>Incident Type</th>
                            <th style="text-align: right;">Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($type_breakdown as $type)
                            <tr>
                                <td>{{ $type->incident_type }}</td>
                                <td style="text-align: right; font-weight: bold;">{{ $type->aggregate_count }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="2" style="text-align: center; color: #718096; padding: 10px;">No incident types recorded.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </td>
        </tr>
    </table>

    <div class="section-header">Incidents Registry</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>No.</th>
                <th>Blotter No.</th>
                <th>Incident Type</th>
                <th>Date & Location</th>
                <th>Involved Parties</th>
                <th>Officer In-Charge</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($blotters as $index => $blotter)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td style="font-weight: bold; color: #1a365d;">{{ $blotter->blotter_number }}</td>
                    <td style="font-weight: bold;">{{ $blotter->incident_type }}</td>
                    <td>
                        {{ \Carbon\Carbon::parse($blotter->incident_date)->format('M d, Y h:i A') }}<br>
                        <small style="color: #4a5568;">At: {{ $blotter->incident_location }}</small>
                    </td>
                    <td>
                        @php
                            $complainants = $blotter->parties->where('role', 'complainant')->pluck('full_name')->toArray();
                            $respondents = $blotter->parties->where('role', 'respondent')->pluck('full_name')->toArray();
                        @endphp
                        @if(count($complainants) > 0)
                            <small><strong>Complainant:</strong> {{ implode(', ', $complainants) }}</small><br>
                        @endif
                        @if(count($respondents) > 0)
                            <small><strong>Respondent:</strong> {{ implode(', ', $respondents) }}</small>
                        @endif
                    </td>
                    <td>{{ $blotter->officer ? $blotter->officer->name : 'Unassigned' }}</td>
                    <td>
                        @if($blotter->status === 'filed')
                            <span class="status-badge" style="background-color: #e2e8f0; color: #475569;">Filed</span>
                        @elseif($blotter->status === 'under_investigation')
                            <span class="status-badge" style="background-color: #ffedd5; color: #ea580c;">Investigation</span>
                        @elseif($blotter->status === 'settled')
                            <span class="status-badge" style="background-color: #dcfce7; color: #166534;">Settled</span>
                        @else
                            <span class="status-badge" style="background-color: #fee2e2; color: #991b1b;">Escalated</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center; color: #718096; padding: 20px;">No blotter incidents registered matching filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <table class="sig-table">
        <tr>
            <td class="sig-block">
                <div style="font-size: 10px; margin-bottom: 25px;">Prepared by:</div>
                <div style="font-weight: bold;">{{ strtoupper($generated_by_name) }}</div>
                <div style="font-size: 9px; color: #555;">Barangay Personnel / Staff</div>
            </td>
            <td class="sig-block">
                <div style="font-size: 10px; margin-bottom: 25px;">Attested by:</div>
                <div class="sig-line"></div>
                <div style="font-weight: bold;">HON. JUAN DELA CRUZ</div>
                <div style="font-size: 9px; color: #555;">Barangay Chairman</div>
            </td>
        </tr>
    </table>

    <div class="footer" style="text-align: center; margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 10px;">
        <p style="margin: 0;">Barangay San Jose Information System — Confidential Administrative Document</p>
    </div>

</body>
</html>
